### ISSUE TITLE
Window undefined on Gatsby build time

### ISSUE THREAD

**Issue by DevanB** [wojtekmaj/react-fit#1]
When using react-time-picker, react-fit is doing a [check against `window`](
https://github.com/wojtekmaj/react-fit/blob/master/src/Fit.jsx#L8) however it is undefined. This is because Gatsby is rendering (at build time) in Node, not in a browser.

In the meantime, I am setting [this up](
https://www.gatsbyjs.org/docs/debugging-html-builds/#fixing-third-party-modules) to bypass the error.

**Comment by wojtekmaj** [comment]
Should be fixed in v1.0.4, please confirm.
