### ISSUE TITLE
Warning: <Fit />'s child needed to have its height decreased to xxx.px.

### ISSUE THREAD

**Issue by msterba-vendavo** [wojtekmaj/react-fit#142]
We use this component in cases where there can be less space available and child element of Fit is scrollable then. But We are getting this warning

Warning: <Fit />'s child needed to have its height decreased to

into to Chrome developer console and it does not look nice. 

I propose change the log level of this message to "verbose" or to do it configurable.

![image](https://github.com/user-attachments/assets/79866f0a-1330-4b41-b8a8-ace51d2c01b8)

**Comment by wojtekmaj** [comment]
Kinda duplicate of #10, but I see how configurable verbosity should reduce annoyance, so let's say it's a feature request :D

**Comment by msterba-vendavo** [comment]
Yes, at least in Chrome, by default dev console show 3 levels of messages except verbose. and it is a bit scary to see these red massages in dev console. And yes, annoying.
thank you Wojtek. Hope it will be done soon :-)
